// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreateLessons implements pgx.CopyFromSource.
type iteratorForCreateLessons struct {
	rows                 []CreateLessonsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLessons) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLessons) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Hash,
		r.rows[0].SubjectID,
		r.rows[0].Category,
		r.rows[0].Day,
		r.rows[0].TimeStart,
		r.rows[0].TimeEnd,
		r.rows[0].RepeatRule,
		r.rows[0].TimetableID,
	}, nil
}

func (r iteratorForCreateLessons) Err() error {
	return nil
}

func (q *Queries) CreateLessons(ctx context.Context, arg []CreateLessonsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lessons"}, []string{"hash", "subject_id", "category", "day", "time_start", "time_end", "repeat_rule", "timetable_id"}, &iteratorForCreateLessons{rows: arg})
}

// iteratorForCreateLocations implements pgx.CopyFromSource.
type iteratorForCreateLocations struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateLocations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateLocations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateLocations) Err() error {
	return nil
}

func (q *Queries) CreateLocations(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"locations"}, []string{"name"}, &iteratorForCreateLocations{rows: name})
}

// iteratorForCreateSubgroups implements pgx.CopyFromSource.
type iteratorForCreateSubgroups struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSubgroups) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSubgroups) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateSubgroups) Err() error {
	return nil
}

func (q *Queries) CreateSubgroups(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subgroups"}, []string{"name"}, &iteratorForCreateSubgroups{rows: name})
}

// iteratorForCreateSubjects implements pgx.CopyFromSource.
type iteratorForCreateSubjects struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSubjects) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSubjects) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateSubjects) Err() error {
	return nil
}

func (q *Queries) CreateSubjects(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subjects"}, []string{"name"}, &iteratorForCreateSubjects{rows: name})
}

// iteratorForCreateTeachers implements pgx.CopyFromSource.
type iteratorForCreateTeachers struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTeachers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTeachers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForCreateTeachers) Err() error {
	return nil
}

func (q *Queries) CreateTeachers(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"teachers"}, []string{"name"}, &iteratorForCreateTeachers{rows: name})
}

// iteratorForCreateTimetables implements pgx.CopyFromSource.
type iteratorForCreateTimetables struct {
	rows                 []CreateTimetablesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTimetables) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTimetables) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].DateStart,
		r.rows[0].DateEnd,
	}, nil
}

func (r iteratorForCreateTimetables) Err() error {
	return nil
}

func (q *Queries) CreateTimetables(ctx context.Context, arg []CreateTimetablesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"timetables"}, []string{"name", "date_start", "date_end"}, &iteratorForCreateTimetables{rows: arg})
}
