// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForCreateSubgroupAssignments implements pgx.CopyFromSource.
type iteratorForCreateSubgroupAssignments struct {
	rows                 []CreateSubgroupAssignmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSubgroupAssignments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSubgroupAssignments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LessonID,
		r.rows[0].SubgroupID,
	}, nil
}

func (r iteratorForCreateSubgroupAssignments) Err() error {
	return nil
}

func (q *Queries) CreateSubgroupAssignments(ctx context.Context, arg []CreateSubgroupAssignmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subgroups_assignments"}, []string{"lesson_id", "subgroup_id"}, &iteratorForCreateSubgroupAssignments{rows: arg})
}

// iteratorForCreateTeacherLocationAssignments implements pgx.CopyFromSource.
type iteratorForCreateTeacherLocationAssignments struct {
	rows                 []CreateTeacherLocationAssignmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateTeacherLocationAssignments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateTeacherLocationAssignments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].LessonID,
		r.rows[0].TeacherID,
		r.rows[0].LocationID,
	}, nil
}

func (r iteratorForCreateTeacherLocationAssignments) Err() error {
	return nil
}

func (q *Queries) CreateTeacherLocationAssignments(ctx context.Context, arg []CreateTeacherLocationAssignmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"teacher_location_assignments"}, []string{"lesson_id", "teacher_id", "location_id"}, &iteratorForCreateTeacherLocationAssignments{rows: arg})
}

// iteratorForInsertStagingLessons implements pgx.CopyFromSource.
type iteratorForInsertStagingLessons struct {
	rows                 []InsertStagingLessonsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingLessons) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingLessons) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StagingID,
		r.rows[0].Subject,
		r.rows[0].Category,
		r.rows[0].Day,
		r.rows[0].TimeStart,
		r.rows[0].TimeEnd,
		r.rows[0].RepeatRule,
		r.rows[0].Timetable,
	}, nil
}

func (r iteratorForInsertStagingLessons) Err() error {
	return nil
}

func (q *Queries) InsertStagingLessons(ctx context.Context, arg []InsertStagingLessonsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"lessons_staging"}, []string{"staging_id", "subject", "category", "day", "time_start", "time_end", "repeat_rule", "timetable"}, &iteratorForInsertStagingLessons{rows: arg})
}

// iteratorForInsertStagingLocations implements pgx.CopyFromSource.
type iteratorForInsertStagingLocations struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingLocations) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingLocations) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertStagingLocations) Err() error {
	return nil
}

func (q *Queries) InsertStagingLocations(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"locations_staging"}, []string{"name"}, &iteratorForInsertStagingLocations{rows: name})
}

// iteratorForInsertStagingSubgroups implements pgx.CopyFromSource.
type iteratorForInsertStagingSubgroups struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingSubgroups) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingSubgroups) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertStagingSubgroups) Err() error {
	return nil
}

func (q *Queries) InsertStagingSubgroups(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subgroups_staging"}, []string{"name"}, &iteratorForInsertStagingSubgroups{rows: name})
}

// iteratorForInsertStagingSubgroupsAssignments implements pgx.CopyFromSource.
type iteratorForInsertStagingSubgroupsAssignments struct {
	rows                 []InsertStagingSubgroupsAssignmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingSubgroupsAssignments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingSubgroupsAssignments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StagingID,
		r.rows[0].Subgroup,
	}, nil
}

func (r iteratorForInsertStagingSubgroupsAssignments) Err() error {
	return nil
}

func (q *Queries) InsertStagingSubgroupsAssignments(ctx context.Context, arg []InsertStagingSubgroupsAssignmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subgroups_assignments_staging"}, []string{"staging_id", "subgroup"}, &iteratorForInsertStagingSubgroupsAssignments{rows: arg})
}

// iteratorForInsertStagingSubjects implements pgx.CopyFromSource.
type iteratorForInsertStagingSubjects struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingSubjects) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingSubjects) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertStagingSubjects) Err() error {
	return nil
}

func (q *Queries) InsertStagingSubjects(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"subjects_staging"}, []string{"name"}, &iteratorForInsertStagingSubjects{rows: name})
}

// iteratorForInsertStagingTeacherLocationAssignments implements pgx.CopyFromSource.
type iteratorForInsertStagingTeacherLocationAssignments struct {
	rows                 []InsertStagingTeacherLocationAssignmentsParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingTeacherLocationAssignments) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingTeacherLocationAssignments) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].StagingID,
		r.rows[0].Teacher,
		r.rows[0].Location,
	}, nil
}

func (r iteratorForInsertStagingTeacherLocationAssignments) Err() error {
	return nil
}

func (q *Queries) InsertStagingTeacherLocationAssignments(ctx context.Context, arg []InsertStagingTeacherLocationAssignmentsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"teacher_location_assignments_staging"}, []string{"staging_id", "teacher", "location"}, &iteratorForInsertStagingTeacherLocationAssignments{rows: arg})
}

// iteratorForInsertStagingTeachers implements pgx.CopyFromSource.
type iteratorForInsertStagingTeachers struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingTeachers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingTeachers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertStagingTeachers) Err() error {
	return nil
}

func (q *Queries) InsertStagingTeachers(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"teachers_staging"}, []string{"name"}, &iteratorForInsertStagingTeachers{rows: name})
}

// iteratorForInsertStagingTimetables implements pgx.CopyFromSource.
type iteratorForInsertStagingTimetables struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForInsertStagingTimetables) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertStagingTimetables) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForInsertStagingTimetables) Err() error {
	return nil
}

func (q *Queries) InsertStagingTimetables(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"timetables_staging"}, []string{"name"}, &iteratorForInsertStagingTimetables{rows: name})
}
