// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
)

type Lesson struct {
	ID          uuid.UUID
	Hash        string
	SubjectID   int32
	Category    string
	Day         int32
	TimeStart   int32
	TimeEnd     int32
	RepeatRule  int32
	TimetableID int32
}

type Location struct {
	ID   int32
	Name string
}

type Subgroup struct {
	ID   int32
	Name string
}

type SubgroupsAssignment struct {
	LessonID   uuid.UUID
	SubgroupID int32
}

type Subject struct {
	ID   int32
	Name string
}

type Teacher struct {
	ID   int32
	Name string
}

type TeacherLocationAssignment struct {
	LessonID   uuid.UUID
	TeacherID  int32
	LocationID int32
}

type Timetable struct {
	ID        int32
	Name      string
	DateStart time.Time
	DateEnd   time.Time
}
