// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Lesson struct {
	ID          uuid.UUID
	SubjectID   int32
	Category    string
	Day         int32
	TimeStart   int32
	TimeEnd     int32
	RepeatRule  int32
	TimetableID int32
	Hash        string
}

type LessonsStaging struct {
	StagingID  uuid.UUID
	Subject    string
	Category   string
	Day        int32
	TimeStart  int32
	TimeEnd    int32
	RepeatRule int32
	Timetable  string
	Hash       pgtype.Text
}

type Location struct {
	ID   int32
	Name string
}

type LocationsStaging struct {
	Name string
}

type Subgroup struct {
	ID   int32
	Name string
}

type SubgroupsAssignment struct {
	LessonID   uuid.UUID
	SubgroupID int32
}

type SubgroupsAssignmentsStaging struct {
	StagingID uuid.UUID
	Subgroup  string
}

type SubgroupsStaging struct {
	Name string
}

type Subject struct {
	ID   int32
	Name string
}

type SubjectsStaging struct {
	Name string
}

type Teacher struct {
	ID   int32
	Name string
}

type TeacherLocationAssignment struct {
	LessonID   uuid.UUID
	TeacherID  int32
	LocationID int32
}

type TeacherLocationAssignmentsStaging struct {
	StagingID uuid.UUID
	Teacher   string
	Location  string
}

type TeachersStaging struct {
	Name string
}

type Timetable struct {
	ID        int32
	Name      string
	DateStart time.Time
	DateEnd   time.Time
	Week      int32
}

type TimetablesStaging struct {
	Name string
}
